<a href="https://colab.research.google.com/github/youuRee/DeepLearning_Lecture/blob/main/CH2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2-1: Dense Layers

In [2]:
# Code.2-1-1: Shapes of Dense Layers

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 1, 10
X = tf.random.normal(shape=(N, n_feature)) # X's row vestor = N(1) * n_feature(10)

n_neuron = 3 # weights metrix = 10 * 3, bias row vector = 1 * 10
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('===== Input/Weights/Bias =====')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

===== Input/Weights/Bias =====
X:  (1, 10)
W:  (10, 3)
B:  (3,)
Y:  (1, 3)


In [6]:
# Code.2-1-2: Output Calculations

import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature)) # X's row vestor = N(1) * n_feature(10)

n_neuron = 3 # weights metrix = 10 * 3, bias row vector = 1 * 10
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensotflow): \n", Y_tf.numpy())

# calculate with matrix multplication
z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-z))
print("Y(with matrix multiolication): \n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensotflow): 
 [[0.3374349  0.8389372  0.8717373 ]
 [0.553568   0.95240414 0.6866497 ]
 [0.07051834 0.05846536 0.12135008]
 [0.7909593  0.28545392 0.667162  ]]
Y(with matrix multiolication): 
 [[0.3374349  0.8389372  0.8717373 ]
 [0.553568   0.952404   0.6866497 ]
 [0.07051836 0.05846533 0.12135009]
 [0.7909593  0.28545392 0.667162  ]]
Y(with dot products): 
 [[0.33743486 0.83893724 0.8717373 ]
 [0.55356808 0.95240405 0.6866497 ]
 [0.07051836 0.05846531 0.12135012]
 [0.79095932 0.2854539  0.66716203]]


2-2: Cascaded Dense Layers

In [9]:
# Code.2-2-1: Shapes of Cacaded Dense Layers

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weights/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {}\n".format(X.shape))

print("W1: {}\n".format(W1.shape))
print("B1: {}\n".format(B1.shape))
print("A1: {}\n".format(A1.shape))

print("W2: {}\n".format(W2.shape))
print("B2: {}\n".format(B2.shape))
print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1: (10, 3)

B1: (3,)

A1: (4, 3)

W2: (3, 5)

B2: (5,)

Y: (4, 5)

