### Shape of Conv Layers

In [25]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 5 # input image = 28X28X5, n_C: 깊이
n_filter = 1 # 뉴런의 개수
k_size = 3 # 커널 = 3X3X5

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))


conv =  Conv2D(filters =n_filter,kernel_size=k_size)

y = conv(images) # 커널 통과힌 결과

W, B = conv.get_weights()


print (image.shape)
print (W.shape)
print(B.shape)
print (y.shape)

(1, 28, 28, 5)
(3, 3, 5, 1)
(1,)
(1, 26, 26, 1)


### Correlation Calculation

In [26]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))


conv =  Conv2D(filters =n_filter,kernel_size=k_size)

y = conv(images)
print("Y(Tensorflow) : \n",y.numpy().squeeze())
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i : i+k_size, j : j+k_size]
        y_man[i, j] = np.sum(window*W) + B
        
print("Y(Manual): \n", y_man)

Y(Tensorflow) : 
 [[ 0.44109568  0.24300475  0.36228997]
 [ 0.6125108   0.04371722  0.5127007 ]
 [ 0.3571732  -0.05183658  0.24013679]]
Y(Manual): 
 [[ 0.44109568  0.24300475  0.36228994]
 [ 0.6125108   0.04371723  0.51270068]
 [ 0.3571732  -0.05183658  0.24013677]]


### Correlation with n-channel

In [29]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                          shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
print("Y(Tensorflow): \n", y.numpy().squeeze())
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()
y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
    window = images[i : i+k_size, j : j+k_size]
    y_man[i, j] = np.sum(window*W) + B


print("Y(Manual): \n", y_man)

Y(Tensorflow): 
 [[0.6412274  0.90759146 0.8077132 ]
 [0.7218005  1.0016291  0.82218623]
 [0.61645126 0.5086763  0.5091823 ]]
Y(Manual): 
 [[0.64122742 0.90759152 0.80771321]
 [0.72180051 1.00162911 0.82218623]
 [0.6164512  0.50867629 0.50918227]]
