<a href="https://colab.research.google.com/github/youuRee/DeepLearning_Lecture/blob/main/Part2_1_CH01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1-1: Affine Functions with 1 Feature

In [ ]:
# Code.1-1-1: Affine Function

import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]])

dense = Dense(units=1, activation='linear')

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

print('===== Input/weight/bias =====')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print('===== Output =====')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

===== Input/weight/bias =====
x: (1, 1)
[[10.]]

W: (1, 1)
[[1.3821293]]

B: (1,)
[0.]

===== Output =====
y(Tensorflow): (1, 1)
[[13.821293]]

y(Manual): (1, 1)
[[13.821293]]



In [ ]:
# Code.1-1-2: Params Initialization

import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant # Constant -> 원하는 값으로 initializers(초기화)

x = tf.constant([[10.]])

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.) # 텐서플로우는 기본적으로 float -> 따라서 10.
w_init, b_init = Constant(w), Constant(b)

# imp. an affine function
dense = Dense(units=1, activation='linear',
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)
print(y_tf) # x(10) * w(10) + b(20)
W, B = dense.get_weights()

# print result
print("W: {}\n{}\n".format(W.shape, w))
print("B: {}\n{}\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
10.0

B: (1,)
[20.]



1-2: Affine Function with n Features

In [ ]:
# Code.1-2-1: Affine Function with n Features

import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = Dense(units=1)

y_tf = dense(x) # dense 통과하면

W, B = dense.get_weights() # 알아서 값 초기화

y_man = tf.linalg.matmul(x, W) + B # 검증

print('===== Input/weight/bias =====')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

print('===== Output =====')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

===== Input/weight/bias =====
x: (1, 10)
[[1.0598993 7.5630894 7.055354  3.1010783 1.3771653 8.337134  1.8225026
  8.521214  4.457915  5.052302 ]]

W: (10, 1)
[[-0.70097405]
 [-0.6954211 ]
 [ 0.50150126]
 [-0.5200922 ]
 [-0.26694354]
 [ 0.24785411]
 [-0.3196708 ]
 [ 0.66107184]
 [-0.62230635]
 [ 0.17245418]]

B: (1,)
[0.]

===== Output =====
y(Tensorflow): (1, 1)
[[0.7693321]]

y(Manual): (1, 1)
[[0.7693321]]



1-3: Activation Function

In [ ]:
# Code.1-3-1: Activation Layer

import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1, 5))

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(Tensorderflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x) / exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorderflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorderflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("Relu(Tensorderflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("Relu(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[ 0.6952397   1.0264286  -1.5441062   0.43331563 -0.37669703]]
Sigmoid(Tensorderflow): (1, 5)
[[0.6671315  0.73622286 0.17593914 0.60666513 0.40692377]]
Sigmoid(Manual): (1, 5)
[[0.66713154 0.7362229  0.17593914 0.60666513 0.40692377]]
Tanh(Tensorderflow): (1, 5)
[[ 0.60133755  0.7724721  -0.9128079   0.4080885  -0.35983557]]
Tanh(Manual): (1, 5)
[[  2.2541883    3.0209966  -17.040543     1.7703534    0.01938903]]
Relu(Tensorderflow): (1, 5)
[[0.6952397  1.0264286  0.         0.43331563 0.        ]]
Relu(Manual): (1, 5)
[[0.6952397  1.0264286  0.         0.43331563 0.        ]]


In [ ]:
# Code.1-3-2: Activation in Dense Layer

import tensorflow as tf
from tensorflow.math import exp
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5)) # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with Relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# forward propation(manual)
print('\n=====\n')

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))
print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(menual): {}\n{}".format(a.shape, a.numpy()))


AN with Sigmoid: (1, 1)
[[0.7787707]]
AN with Tanh: (1, 1)
[[0.956159]]
AN with Relu: (1, 1)
[[0.]]

=====

Activation value(Tensorflow): (1, 1)
[[0.7787707]]
Activation value(menual): (1, 1)
[[0.7787707]]


1-4: Artificial Neurons

In [ ]:
# Code.1-4-1: Artificial Neurons

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape = (1, 10)) # input setting

dense = Dense(units=1, activation=activation) # imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation valie manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
  y_man = maximum(y_man, 0)

print('Activation: ', activation)
print('y_tf: {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y_man: {}\n{}\n'.format(y_man.shape, y_man.numpy()))

Activation:  sigmoid
y_tf: (1, 1)
[[0.29830763]]

y_man: (1, 1)
[[0.29830763]]



1-5: Minibatches

In [ ]:
# Code.1-5-1: Shapes of Dense Layers

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 32000, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatche

dense = Dense(units=1, activation='relu') # imp. an AN
y = dense(x) # forward propagation

W, B = dense.get_weights() # get weights/bias

# print result
print('Shape of x: ', x.shape)
print('Shape of W: ', W.shape)
print('Shape of B: ', B.shape)

Shape of x:  (32000, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


In [ ]:
# Code.1-5-2: Output Calculation

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input params
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation='sigmoid') # imp. an AN
y_tf = dense(x) # forward propagation(Tensorflow)

W, B = dense.get_weights() # get weights/bias

y_man = tf.linalg.matmul(x, W) + B # forward propagation(Manual)
y_man = 1 / (1 + tf.math.exp(-y_man))

# print result
print('Output(Tensorflow): \n', y_tf.numpy())
print('Output(Manual): \n', y_man.numpy())

Output(Tensorflow): 
 [[0.74493295]
 [0.7081195 ]
 [0.78175646]
 [0.14136732]
 [0.32922256]
 [0.29196122]
 [0.19100147]
 [0.24145672]]
Output(Manual): 
 [[0.74493295]
 [0.7081195 ]
 [0.78175646]
 [0.14136733]
 [0.3292226 ]
 [0.2919612 ]
 [0.19100149]
 [0.24145672]]
