<a href="https://colab.research.google.com/github/youuRee/DeepLearning_Lecture/blob/main/Part2_1_CH02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2-1: Dense Layers

In [ ]:
# Code.2-1-1: Shapes of Dense Layers

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 1, 10
X = tf.random.normal(shape=(N, n_feature)) # X's row vestor = N(1) * n_feature(10)

n_neuron = 3 # weights metrix = 10 * 3, bias row vector = 1 * 10
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('===== Input/Weights/Bias =====')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

===== Input/Weights/Bias =====
X:  (1, 10)
W:  (10, 3)
B:  (3,)
Y:  (1, 3)


In [ ]:
# Code.2-1-2: Output Calculations

import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature)) # X's row vestor = N(1) * n_feature(10)

n_neuron = 3 # weights metrix = 10 * 3, bias row vector = 1 * 10
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensotflow): \n", Y_tf.numpy())

# calculate with matrix multplication
z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-z))
print("Y(with matrix multiolication): \n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensotflow): 
 [[0.3374349  0.8389372  0.8717373 ]
 [0.553568   0.95240414 0.6866497 ]
 [0.07051834 0.05846536 0.12135008]
 [0.7909593  0.28545392 0.667162  ]]
Y(with matrix multiolication): 
 [[0.3374349  0.8389372  0.8717373 ]
 [0.553568   0.952404   0.6866497 ]
 [0.07051836 0.05846533 0.12135009]
 [0.7909593  0.28545392 0.667162  ]]
Y(with dot products): 
 [[0.33743486 0.83893724 0.8717373 ]
 [0.55356808 0.95240405 0.6866497 ]
 [0.07051836 0.05846531 0.12135012]
 [0.79095932 0.2854539  0.66716203]]


2-2: Cascaded Dense Layers

In [ ]:
# Code.2-2-1: Shapes of Cacaded Dense Layers

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weights/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {}\n".format(X.shape))

print("W1: {}\n".format(W1.shape))
print("B1: {}\n".format(B1.shape))
print("A1: {}\n".format(A1.shape))

print("W2: {}\n".format(W2.shape))
print("B2: {}\n".format(B2.shape))
print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1: (10, 3)

B1: (3,)

A1: (4, 3)

W2: (3, 5)

B2: (5,)

Y: (4, 5)



In [ ]:
# Code.2-2-2: Dense Layers with Python List

import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
dense_layers = list()

for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='relu')
  dense_layers.append(dense)

print('Input: ', X.shape)

for dense_idx, dense in enumerate(dense_layers): # enumerate: 인덱스와 원소 동시 접근, (index, 원소) 할당
  X = dense(X)
  print('After dense layer', dense_idx+1)
  print(X.shape, '\n')
Y = X

Input:  (4, 10)
After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 

After dense layer 6
(4, 60) 

After dense layer 7
(4, 70) 

After dense layer 8
(4, 80) 

After dense layer 9
(4, 90) 

After dense layer 10
(4, 100) 



In [ ]:
# Code.2-2-3: Output Calculation

import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X) # X를 복사

n_neurons = [3, 4, 5]
dense_layers = list()

for n_neuron in n_neurons:
  dense = Dense(units=n_neuron, activation='sigmoid')
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers): # enumerate: 인덱스와 원소 동시 접근, (index, 원소) 할당
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)

print('Y(Tensorflow): \n', X.numpy())

# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))

print('Y(Manmul): \n', X_cp.numpy())

Y(Tensorflow): 
 [[0.67852825 0.70646363 0.587519   0.30788428 0.48369282]
 [0.68134487 0.7127404  0.60265166 0.3085062  0.50906956]
 [0.67237014 0.70281637 0.6041     0.31456006 0.50714386]
 [0.6610224  0.6877475  0.5938591  0.32353073 0.4942216 ]]
Y(Manmul): 
 [[0.67852825 0.70646363 0.587519   0.30788428 0.48369285]
 [0.6813449  0.71274036 0.6026516  0.30850616 0.50906956]
 [0.67237014 0.70281637 0.6041     0.31456006 0.5071438 ]
 [0.6610224  0.68774754 0.59385914 0.3235307  0.4942216 ]]


2-3: Model Implementation

In [ ]:
# Code.2-3-1: Model Implementation with Sequential Method

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model = Sequential() # layer object들을 포함 (layer들이 sequential하게 연결됨)
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

In [ ]:
# Code.2-3-2: Model Implementation with Model-subclassing(상속) 

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

# 텐서플로우에서 제공하는 모델 상속받기
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()

In [ ]:
# Code.2-3-3: Forward Propagation of Model

import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape=(4, 10))

# sequenial method
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

# Model-subclassing
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return X

model = TestModel()
Y = model(X)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[-0.77538806, -0.79431814,  1.1242169 , -0.16516745, -1.7533065 ,
         0.83931863, -0.34323192,  1.7822747 , -0.92974985, -0.2061417 ],
       [-2.1029775 ,  0.14482184, -1.3477298 , -1.2315358 , -1.9620634 ,
         0.8213118 ,  1.139046  ,  0.27639607, -0.30839702,  1.2043407 ],
       [-0.6237425 , -0.5489391 , -0.8195602 ,  1.1156944 , -1.5193105 ,
        -0.61323917, -1.3036895 , -0.29999664,  0.8427249 ,  0.6045288 ],
       [ 0.09045117,  0.9476534 ,  0.4800321 ,  0.49775457, -1.3111477 ,
        -0.11441507, -0.02337359,  0.5959432 , -0.908235  ,  0.75575674]],
      dtype=float32)>

In [ ]:
# +
class TestModel(Model):
  super(TestModel, self).__init__()
  self.n_neurons = n_neurons

  self.dense_layer = list()
  for n_neuron in self.n_neurons:
    self.dense_layers.append(Dense(units=n_neuron, activation='sigmoid'))

  def call(self, x):
    for dense in self.dense_layers:
      x = dense(x)
    return x
  
class TestModel(Model):
  super(TestModel, self).__init__()
  self.n_neurons = n_neurons

  self.model = Sequential()
  self.model.add(Dense(units=10, activation='sigmoid'))
  self.model.add(Dense(units=20, activation='sigmoid'))

  def call(self, x):
    x = self.model(x)
    return x

n_neurons = [3, 4, 5]
model = TestModel(n_neurons)

In [3]:
# Code.2-3-4: Layers in Models

import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.layers))
print(model.layers)

for layer in model.layers:
  w, b = layer.get_weights()
  print(w.shape, b.shape)

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7f598b93f450>, <keras.layers.core.dense.Dense object at 0x7f598b93ff90>]
(10, 10) (10,)
(10, 20) (20,)


In [4]:
# Code.2-3-5: Trainable Variables in Models

import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.trainable_variables)) # trainable_variables 안에 w, b 값 포함
print(len(model.trainable_variables))

for train_var in model.trainable_variables:
  print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
