### Shapes woth Filters

In [12]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 26, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                            shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W,B = conv.get_weights()

print("Input Image: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Image: (32, 28, 26, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 24, 5)


# Computation with Filters

Y = conv(images)  
Y(Tensorflow): Y.numpy()  
=> shape: (1, 2, 2, 3) = 2x2 (row,cols) 이미지의 3개의 요소(R, G, B)  
=> row가 위에 있는 행렬

In [16]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, nc = 1, 5, 5, 3
n_filter = 3
k_size = 4
images = tf.random.uniform(minval=0, maxval=1,
                          shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y)

Y(Tensorflow): 
 [[[ 0.6881267   0.72664636]
  [ 0.32433972  0.77794385]]

 [[-0.6957755  -0.85192794]
  [-0.8024278  -1.3178432 ]]

 [[-0.14701244  0.01147318]
  [ 0.17515545  0.43173367]]]


### Conv Layers with Activation Functions

In [21]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, nc = 1, 5, 5, 3
n_filter = 3
k_size = 4
image = tf.random.uniform(minval=0, maxval=1,
                          shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation = 'sigmoid')
Y = conv(image)
Y  = np.transpose(Y.numpy().squeeze(),(2,0,1))
print("Y(Tensorflow):\n",Y)

#Forward Propagation(Manual)
W, B = conv.get_weights()
image = image.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
      c_W=W[:,:,:,c]
      c_b = B[c]
      for h in range(n_H - k_size + 1):
          for j in range(n_W - k_size + 1):
            window = image[h:h+k_size, j:j+k_size, :]
            conv = np.sum(window*c_W) + c_b
            conv = 1/(1 +np.exp(-conv))

            Y_man[h,j,c] = conv
print("Y(Manual) :\n",np.transpose(Y_man,(2,0,1)))

Y(Tensorflow):
 [[[0.5673084  0.40961263]
  [0.6415513  0.38765982]]

 [[0.6091399  0.7300606 ]
  [0.6089905  0.5614381 ]]

 [[0.58337426 0.7221749 ]
  [0.4651717  0.6130379 ]]]
Y(Manual) :
 [[[0.56730845 0.40961262]
  [0.64155131 0.3876598 ]]

 [[0.60913996 0.73006057]
  [0.60899047 0.56143811]]

 [[0.58337436 0.7221749 ]
  [0.46517166 0.61303783]]]
