<a href="https://colab.research.google.com/github/youuRee/DeepLearning_Lecture/blob/main/Max_and_Average_Pooling_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Max Pooling

In [5]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1 # f: window를 몇개씩 묶을건지, s(strides): window를 몇칸씩 띌건지

x = tf.random.normal(shape=(1, L, 1)) # 1 x L vector

pool_max = MaxPooling1D(pool_size=f, strides=s) # f=1 -> 1 x 1 shape
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                        pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print("pooled max(Manual): {}\n{}".format (pooled_max_man.shape,
                                            pooled_max_man))

x: (1, 10, 1)
[ 0.49707216 -0.60469514 -1.0814945  -1.5263816  -0.04543524  0.3618649
 -0.31423506  0.5992497  -1.0249035   0.07633875]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.49707216 -0.60469514 -1.0814945  -0.04543524  0.3618649   0.3618649
  0.5992497   0.5992497   0.07633875]
pooled max(Manual): (9,)
[ 0.49707216 -0.60469514 -1.08149445 -0.04543524  0.36186489  0.36186489
  0.59924972  0.59924972  0.07633875]


### Average Pooling

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))

pool_avg = MaxPooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                        pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L - f + 1, ))
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                            pooled_avg_man))

x: (1, 10, 1)
[-1.0037761  -1.0361043   0.73231465 -0.1697108  -0.30194202  2.4482028
 -1.2187166  -1.3861419  -0.48639384  1.0278198 ]
pooled_avg(Tensorflow): (1, 9, 1)
[-1.0037761   0.73231465  0.73231465 -0.1697108   2.4482028   2.4482028
 -1.2187166  -0.48639384  1.0278198 ]
pooled_avg(Manual): (9,)
[-1.01994014 -0.15189484  0.28130192 -0.2358264   1.07313037  0.61474311
 -1.3024292  -0.93626785  0.27071297]


### 2D Max/Avg Pooling

In [16]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C =1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))

pool_max = MaxPooling2D(pool_size = f, strides=s) # f=2 -> 2 x 2 shape
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled max(Tensorflow): {}\n{}". format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))
x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
    for j in range(n_W - f + 1):
        window = x[i:i+f,j:j+f]
        pooled_max_man[i, j] = np.max(window)

print("pooled max(Manual): {}\n{}".format(pooled_max_man.shape, 
                                          pooled_max_man))

x: (1, 5, 5, 1)
[[-0.13338763 -0.5453655   0.46082142  1.4656358   0.6979022 ]
 [-0.55690205  0.7628222   0.66231686  0.71250296 -0.8059913 ]
 [-0.3210735   0.03913952 -0.13616514  0.8002857   1.2321188 ]
 [-1.6400495   0.22539862  0.12130111  0.22061998  0.6112773 ]
 [ 0.2654617   0.14959763  0.5008948  -0.670768    2.3123882 ]]
pooled max(Tensorflow): (1, 4, 4, 1)
[[0.7628222  0.7628222  1.4656358  1.4656358 ]
 [0.7628222  0.7628222  0.8002857  1.2321188 ]
 [0.22539862 0.22539862 0.8002857  1.2321188 ]
 [0.2654617  0.5008948  0.5008948  2.3123882 ]]
pooled max(Manual): (4, 4)
[[0.76282221 0.76282221 1.46563578 1.46563578]
 [0.76282221 0.76282221 0.8002857  1.23211884]
 [0.22539862 0.22539862 0.8002857  1.23211884]
 [0.26546171 0.50089478 0.50089478 2.31238818]]


### 2D Average Pooling

In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C  = 1, 5, 5, 1
f, s =2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W- f + 1))
for i in range(n_H - f + 1):
    for j in range(n_W - f + 1):
      window = x[i:i+f, j:j+f]
      pooled_avg_man[i, j] = np.mean(window)

print("pooled avg(Manual): {}\n{}". format (pooled_avg_man.shape,
                                              pooled_avg_man))

x: (1, 5, 5, 1)
[[-0.25525704 -1.3182727  -0.9093466   1.0057625  -1.413715  ]
 [ 1.350178   -0.01735511 -2.195587    0.45582476  0.7800549 ]
 [ 0.877247    1.3477519  -0.8255786  -1.9918145   1.3495567 ]
 [-1.6101594  -0.9571623   0.12680942  0.7541149   1.3335668 ]
 [-1.1531104   0.55598444  0.46689376 -0.4496002  -0.03744446]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[-0.06017671 -1.1101403  -0.4108366   0.20698178]
 [ 0.88945544 -0.4226922  -1.1392888   0.14840546]
 [-0.08558069 -0.0770449  -0.4841172   0.36135596]
 [-0.79111195  0.04813132  0.22455448  0.40015927]]
pooled avg(Manual): (4, 4)
[[-0.06017671 -1.11014032 -0.41083661  0.20698178]
 [ 0.88945544 -0.42269221 -1.13928878  0.14840546]
 [-0.08558069 -0.0770449  -0.48411721  0.36135596]
 [-0.79111195  0.04813132  0.22455448  0.40015927]]
