<a href="https://colab.research.google.com/github/youuRee/DeepLearning_Lecture/blob/main/Padding_and_Strides.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 3D Max Pooling

In [7]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D
N, n_H, n_W, n_C = 1, 5, 5, 3
f, s= 2, 2

x = tf.random.normal(shape = (N,n_H,n_W,n_C))
# print("x: {}}\{(}°. format (x. shape,
#                               np.transpose(x.numpy().squeeze(), {2, 0, 1))))

pool_max = MaxPooling2D(pool_size=f, strides = s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max_t))
x = x.numpy().squeeze()
n_H_ = math.floor((n_H - f)/s + 1) # floor: 바닥함수(가우스)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))

for c in range(n_C):
      c_image = x[:, :, c]
      h_ = 0
      for h in range(0, n_H - f + 1, s):
        w_=0
        for w in range(0, n_W-f+1 , s):
          window = c_image[h:h+f, w:w+f]
          pooled_max_man[h_, w_, c] = np.max(window)

          w_ +=1
        h_ +=1
pooled_max_t = np.transpose(pooled_max_man, (2, 0, 1))
print("pooled max(Manual): {}\n{}". format (pooled_max_man.shape,
                                            pooled_max_t))

pooled_max(Tensorflow): (1, 2, 2, 3)
[[[-0.21688476  0.81755435]
  [ 1.0875492   1.5872422 ]]

 [[ 1.8509338   0.59053963]
  [ 0.74755836  1.9207478 ]]

 [[-0.44352725  1.3913611 ]
  [ 0.6963096   0.39631042]]]
pooled max(Manual): (2, 2, 3)
[[[-0.21688476  0.81755435]
  [ 1.08754921  1.58724225]]

 [[ 1.85093379  0.59053963]
  [ 0.74755836  1.92074776]]

 [[-0.44352725  1.39136112]
  [ 0.69630963  0.39631042]]]


### ZeroPadding2D Layer

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1, 28, 28, 3))

print (images. shape)
# print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding=2)
y = zero_padding(images)
print (y.shape)
# print(np.transpoge(y.numpy().squeeze(), (2, 0, 1)))

(1, 28, 28, 3)
(1, 32, 32, 3)


### Zero Padding with Conv2D Layers

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))

conv = Conv2D(filters=1, kernel_size=3, padding='same') # same: size가 줄어들지 않도록 자동으로 패딩 배치, valid: padding 안함
y = conv(images)
print(y.shape) # input's shape와 동일

(1, 28, 28, 1)


### strides in Conv2D Layers

In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))

conv = Conv2D(filters=1, kernel_size=3, padding='valid',strides =2)
y = conv(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


### Strides in Pooling Layers

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))

pool = MaxPooling2D(pool_size=3, strides =2)
y = pool(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
